# Generated by Django 4.0.4 on 2022-06-14 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(blank=True, max_length=255, null=True)),
                ('AUTHOR', models.CharField(blank=True, max_length=255, null=True)),
                ('RAITING', models.CharField(blank=True, max_length=255, null=True)),
                ('IMAGE', models.CharField(blank=True, max_length=255, null=True)),
                ('DESCRIPTION_SHORT', models.TextField(blank=True, null=True)),
                ('DESCRIPTION', models.TextField(blank=True, null=True)),
                ('DATE', models.CharField(blank=True, max_length=255, null=True)),
                ('COUNT_RAITING', models.CharField(blank=True, max_length=255, null=True)),
                ('SEARCH_ID', models.CharField(blank=True, max_length=255, null=True)),
                ('CAT', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='FirstApp.category')),
            ],
        ),
    ]
