# Generated by Django 4.0.3 on 2022-06-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='SEARCH_ID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
