# Generated by Django 4.0.3 on 2022-06-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0002_remove_book_author_remove_book_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='DESCRIPTION_SHORT',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='DESCRIPTION',
            field=models.TextField(blank=True, null=True),
        ),
    ]
